# Generated by Django 2.2.28 on 2022-05-05 00:04

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linktypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'link type Translation'},
        ),
        migrations.AlterModelOptions(
            name='nationalitytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'nationality Translation'},
        ),
        migrations.AlterModelOptions(
            name='persontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'person Translation'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'role Translation'},
        ),
        migrations.AlterModelManagers(
            name='linktype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='nationality',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='linktypetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='linktypetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='people.LinkType'),
        ),
        migrations.AlterField(
            model_name='nationalitytranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='nationalitytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='people.Nationality'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='roletranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='roletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='people.Role'),
        ),
    ]
